### ISSUE TITLE
hii

### ISSUE THREAD

**Issue by ZiHengLee** [JarekPo/financial-ui#47]
Are you working on a quantitative project?

**Comment by JarekPo** [comment]
Hi, yes, I plan to perform some analysis on the historical data in the near future.

**Comment by ZiHengLee** [comment]
> Hi, yes, I plan to perform some analysis on the historical data in the near future.

I am working on a quantitative tool and community lonely
, we can form a small team,then we can discuss and improve efficiency,if its ok,u can leave a email or dicord or twitter,we can make detailed comminication

**Comment by JarekPo** [comment]
Sure, here is my email jarekpolowy at yahoo.com
